// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOTk7M7r1IFWnib2okgabXNJOEoWsX8rc',
    appId: '1:493677842738:web:c17555fc6168994b1ec72b',
    messagingSenderId: '493677842738',
    projectId: 'login-test-e6def',
    authDomain: 'login-test-e6def.firebaseapp.com',
    storageBucket: 'login-test-e6def.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCetOs-iu7B8DKLzxRdSB5jBYMVZQHGHNA',
    appId: '1:493677842738:android:f08ad3b11910762a1ec72b',
    messagingSenderId: '493677842738',
    projectId: 'login-test-e6def',
    storageBucket: 'login-test-e6def.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASujZbsyf4j36Af_XqyhQJ9NZywyqEIFY',
    appId: '1:493677842738:ios:32e217d21f48e97c1ec72b',
    messagingSenderId: '493677842738',
    projectId: 'login-test-e6def',
    storageBucket: 'login-test-e6def.appspot.com',
    iosBundleId: 'com.example.loginTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASujZbsyf4j36Af_XqyhQJ9NZywyqEIFY',
    appId: '1:493677842738:ios:63173b8562984e851ec72b',
    messagingSenderId: '493677842738',
    projectId: 'login-test-e6def',
    storageBucket: 'login-test-e6def.appspot.com',
    iosBundleId: 'com.example.loginTest.RunnerTests',
  );
}
